version: "3"
services:
  fullstack:
    build: .
    image: fullstack
    restart: always
    ports:
      - "80:3001"
    volumes:
      - /node_modules
      - /build
    links:
      - mongodb
    networks:
      - fullstacknetwork
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - fullstacknetwork
networks:
  fullstacknetwork:
    driver: bridge